# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Define environment variable for Django to run in unbuffered mode
ENV PYTHONUNBUFFERED 1

# Run the web server on port 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
